=== svn2github/wot-xvm/trunk/src/editor/src/XVM.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by no (no) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="_align">
		<xs:restriction base="xs:string">
			<xs:enumeration value="left"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="right"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="xvmconfig">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="definition" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="author" type="xs:string" minOccurs="0"/>
							<xs:element name="description" type="xs:string" minOccurs="0"/>
							<xs:element name="url" type="xs:string" minOccurs="0"/>
							<xs:element name="date" type="xs:dateTime" minOccurs="0"/>
							<xs:element name="gameVersion" type="xs:string" minOccurs="0"/>
							<xs:element name="modVersion" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="battle" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="showPostmortemTips" type="xs:boolean" minOccurs="0"/>
							<xs:element name="drawGrid" type="xs:boolean" minOccurs="0"/>
							<xs:element name="disableMirroredVehicleIcons" type="xs:boolean" minOccurs="0"/>
							<xs:element name="showPlayerStatistics" type="xs:boolean" minOccurs="0"/>
							<xs:element name="statColorizePanelPlayerNames" type="xs:boolean" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="behaviors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ally" type="_playerStatus" minOccurs="0"/>
							<xs:element name="squad" type="_playerStatus" minOccurs="0"/>
							<xs:element name="teamKiller" type="_playerStatus" minOccurs="0"/>
							<xs:element name="enemy" type="_playerStatus" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="configVersion" type="xs:string" use="required" fixed="1.0.0"/>
			<xs:attribute name="editorVersion" type="xs:string"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="_ca">
		<xs:attribute name="alpha" type="xs:int"/>
		<xs:attribute name="color" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="_xyav">
		<xs:attribute name="x" type="xs:int"/>
		<xs:attribute name="y" type="xs:int"/>
		<xs:attribute name="alpha" type="xs:int"/>
		<xs:attribute name="visible" type="xs:boolean"/>
	</xs:complexType>
	<xs:complexType name="_xyavc">
		<xs:complexContent>
			<xs:extension base="_xyav">
				<xs:attribute name="color" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="_xyavc2">
		<xs:complexContent>
			<xs:extension base="_xyavc">
				<xs:attribute name="lcolor" type="xs:string"/>
				<xs:attribute name="lalpha" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="_xyavcs">
		<xs:complexContent>
			<xs:extension base="_xyavc">
				<xs:sequence>
					<xs:element name="shadow" type="_shadow" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="_xyavcsft">
		<xs:complexContent>
			<xs:extension base="_xyavcs">
				<xs:sequence>
					<xs:element name="font" type="_font" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="text" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="_font">
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="size" type="xs:int"/>
		<xs:attribute name="align" type="_align"/>
	</xs:complexType>
	<xs:complexType name="_shadow">
		<xs:attribute name="size" type="xs:int"/>
		<xs:attribute name="angle" type="xs:int"/>
		<xs:attribute name="distance" type="xs:int"/>
		<xs:attribute name="color" type="xs:string"/>
		<xs:attribute name="alpha" type="xs:int"/>
		<xs:attribute name="strength" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="_viewStatus">
		<xs:sequence>
			<xs:element name="normal" type="_components" minOccurs="0"/>
			<xs:element name="extended" type="_components" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="_playerStatus">
		<xs:sequence>
			<xs:element name="alive" type="_viewStatus" minOccurs="0"/>
			<xs:element name="dead" type="_viewStatus" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="combatScrollTextBehaviorType">
		<xs:complexContent>
			<xs:extension base="_xyavcsft">
				<xs:sequence>
					<xs:element name="speed" type="xs:int" minOccurs="0"/>
					<xs:element name="maxRange" type="xs:int" minOccurs="0"/>
					<xs:element name="damageMessage" type="xs:string" minOccurs="0"/>
					<xs:element name="blowupMessage" type="xs:string" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="contourIconBehaviorType">
		<xs:complexContent>
			<xs:extension base="_xyavcs">
				<xs:attribute name="amount" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="currentHealthBehaviorType">
		<xs:complexContent>
			<xs:extension base="_xyavcsft">
				<xs:attribute name="showMaxValue" type="xs:boolean"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="healthBarBehaviorType">
		<xs:complexContent>
			<xs:extension base="_xyavc2">
				<xs:sequence>
					<xs:element name="border" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="_ca">
									<xs:attribute name="size" type="xs:int"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="fill" type="_ca" minOccurs="0"/>
					<xs:element name="damage" minOccurs="0">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="_ca">
									<xs:attribute name="fade" type="xs:int"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:attribute name="width" type="xs:int"/>
				<xs:attribute name="height" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="vehicleIconBehaviorType">
		<xs:complexContent>
			<xs:extension base="_xyavcs">
				<xs:attribute name="scaleX" type="xs:int"/>
				<xs:attribute name="scaleY" type="xs:int"/>
				<xs:attribute name="maxScale" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="_components">
		<xs:sequence>
			<xs:element name="vehicleIcon" type="vehicleIconBehaviorType" minOccurs="0"/>
			<xs:element name="playerName" type="_xyavcsft" minOccurs="0"/>
			<xs:element name="vehicleName" type="_xyavcsft" minOccurs="0"/>
			<xs:element name="healthBar" type="healthBarBehaviorType" minOccurs="0"/>
			<xs:element name="currentHealth" type="currentHealthBehaviorType" minOccurs="0"/>
			<xs:element name="healthRatio" type="_xyavcsft" minOccurs="0"/>
			<xs:element name="combatScrollText" type="combatScrollTextBehaviorType" minOccurs="0"/>
			<xs:element name="contourIcon" type="contourIconBehaviorType" minOccurs="0"/>
			<xs:element name="levelIcon" type="_xyav" minOccurs="0"/>
			<xs:element name="actionMarker" type="_xyav" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== svn2github/wot-xvm/archive/xvm-1.7/src/editor/src/XVM-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<xvmconfig configVersion="1.0.0" xsi:noNamespaceSchemaLocation="XVM.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<definition>
		<author>String</author>
		<description>String</description>
		<url>String</url>
		<date>2001-12-17T09:30:47Z</date>
		<gameVersion>String</gameVersion>
		<modVersion>String</modVersion>
	</definition>
	<battle>
		<showPostmortemTips>true</showPostmortemTips>
		<disableMirroredVehicleIcons>false</disableMirroredVehicleIcons>
	</battle>
	<behaviors>
		<ally>
			<alive>
				<normal>
					<vehicleIcon alpha="0" color="String" x="0" visible="true" y="0" maxScale="0" scaleX="0" scaleY="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</vehicleIcon>
					<playerName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</playerName>
					<vehicleName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</vehicleName>
					<healthBar alpha="0" color="String" x="0" visible="true" height="0" y="0" width="0" lcolor="String">
						<border alpha="0" color="String" size="0"/>
						<fill alpha="0" color="String"/>
						<damage alpha="0" color="String" fade="0"/>
					</healthBar>
					<currentHealth alpha="0" color="String" text="String" visible="true" x="0" y="0" showMaxValue="true">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</currentHealth>
					<healthRatio alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</healthRatio>
					<combatScrollText alpha="0" color="String" text="String" visible="true" x="0" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
						<speed>0</speed>
						<maxRange>0</maxRange>
						<damageMessage>String</damageMessage>
						<blowupMessage>String</blowupMessage>
					</combatScrollText>
					<contourIcon alpha="0" color="String" x="0" visible="true" y="0" amount="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</contourIcon>
					<levelIcon alpha="0" visible="true" x="0" y="0"/>
					<actionMarker alpha="0" visible="true" x="0" y="0"/>
				</normal>
				<extended>
					<vehicleIcon alpha="0" color="String" x="0" visible="true" y="0" maxScale="0" scaleX="0" scaleY="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</vehicleIcon>
					<playerName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</playerName>
					<vehicleName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</vehicleName>
					<healthBar alpha="0" color="String" x="0" visible="true" height="0" y="0" width="0" lcolor="String">
						<border alpha="0" color="String" size="0"/>
						<fill alpha="0" color="String"/>
						<damage alpha="0" color="String" fade="0"/>
					</healthBar>
					<currentHealth alpha="0" color="String" text="String" visible="true" x="0" y="0" showMaxValue="true">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</currentHealth>
					<healthRatio alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</healthRatio>
					<combatScrollText alpha="0" color="String" text="String" visible="true" x="0" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
						<speed>0</speed>
						<maxRange>0</maxRange>
						<damageMessage>String</damageMessage>
						<blowupMessage>String</blowupMessage>
					</combatScrollText>
					<contourIcon alpha="0" color="String" x="0" visible="true" y="0" amount="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</contourIcon>
					<levelIcon alpha="0" visible="true" x="0" y="0"/>
					<actionMarker alpha="0" visible="true" x="0" y="0"/>
				</extended>
			</alive>
			<dead>
				<normal>
					<vehicleIcon alpha="0" color="String" x="0" visible="true" y="0" maxScale="0" scaleX="0" scaleY="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</vehicleIcon>
					<playerName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</playerName>
					<vehicleName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</vehicleName>
					<healthBar alpha="0" color="String" x="0" visible="true" height="0" y="0" width="0" lcolor="String">
						<border alpha="0" color="String" size="0"/>
						<fill alpha="0" color="String"/>
						<damage alpha="0" color="String" fade="0"/>
					</healthBar>
					<currentHealth alpha="0" color="String" text="String" visible="true" x="0" y="0" showMaxValue="true">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</currentHealth>
					<healthRatio alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</healthRatio>
					<combatScrollText alpha="0" color="String" text="String" visible="true" x="0" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
						<speed>0</speed>
						<maxRange>0</maxRange>
						<damageMessage>String</damageMessage>
						<blowupMessage>String</blowupMessage>
					</combatScrollText>
					<contourIcon alpha="0" color="String" x="0" visible="true" y="0" amount="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</contourIcon>
					<levelIcon alpha="0" visible="true" x="0" y="0"/>
					<actionMarker alpha="0" visible="true" x="0" y="0"/>
				</normal>
				<extended>
					<vehicleIcon alpha="0" color="String" x="0" visible="true" y="0" maxScale="0" scaleX="0" scaleY="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</vehicleIcon>
					<playerName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</playerName>
					<vehicleName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</vehicleName>
					<healthBar alpha="0" color="String" x="0" visible="true" height="0" y="0" width="0" lcolor="String">
						<border alpha="0" color="String" size="0"/>
						<fill alpha="0" color="String"/>
						<damage alpha="0" color="String" fade="0"/>
					</healthBar>
					<currentHealth alpha="0" color="String" text="String" visible="true" x="0" y="0" showMaxValue="true">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</currentHealth>
					<healthRatio alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
					</healthRatio>
					<combatScrollText alpha="0" color="String" text="String" visible="true" x="0" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
						<font align="left" size="0" name="String"/>
						<speed>0</speed>
						<maxRange>0</maxRange>
						<damageMessage>String</damageMessage>
						<blowupMessage>String</blowupMessage>
					</combatScrollText>
					<contourIcon alpha="0" color="String" x="0" visible="true" y="0" amount="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</contourIcon>
					<levelIcon alpha="0" visible="true" x="0" y="0"/>
					<actionMarker alpha="0" visible="true" x="0" y="0"/>
				</extended>
			</dead>
		</ally>
		<squad>
			<alive>
				<normal>
					<vehicleIcon alpha="0" color="String" x="0" visible="true" y="0" maxScale="0" scaleX="0" scaleY="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
					</vehicleIcon>
					<playerName alpha="0" color="String" text="String" x="0" visible="true" y="0">
						<shadow alpha="0" color="String" angle="0" strength="0" distance="0" size="0"/>
